### PR TITLE
Added startup script for windows.

### PR DESCRIPTION
**Pull request by Myster**
The script file needs to be placed in the windows startup folder

### CODE REVIEW

**Comment by NV** [comment]
Would be nice to rewrite [autostart.sh](https://github.com/NV/chrome-devtools-autosave-server/blob/master/scripts/autostart.sh) in JS to make it run on Windows as well.

**Comment by Myster** [comment]
First pull request ever yay, which was mostly copy 'n paste from SO. :-)  
I'm not sure about rewriting autostart.

**Comment by NV** [comment]
Congrats! Could you give a link to SO post? Just for my information.

**Comment by Myster** [comment]
oh it was server fault, here it is:
http://serverfault.com/questions/9038/run-a-bat-file-in-a-scheduled-task-without-a-window

**Pull request merged**
